config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :events
  resources :orgs
  resources :users
  root to: 'application#index'

  # Pages
  get '/about' => 'application#about'

  # Auth & Sessions
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'

  # Orgs
  post '/orgs/new/fb' => 'orgs#new_from_fb'

  # Day View
  get '/events/day/:date' => 'events#show_day'

  # Sentry endpoint for testing
  # get '/sentry' => 'sentry#exception'
end

app/models/org.rb
class Org < ApplicationRecord
  require 'uri'

  filterrific(available_filters: %i[search_query with_category])

  has_and_belongs_to_many :users
  has_many :events, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :category, presence: true
  validate :valid_website?
  validate :valid_photo?

  before_validation :format_url

  scope :search_query, (lambda { |query|
    return nil if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # bracket with '%' to search anywhere in org name
    terms = terms.map { |term| '%' + term + '%' }
    # SQL query
    where(
      terms.map { 'LOWER(orgs.name) LIKE ?' }.join(' AND '),
      *terms.map { |e| [e] }.flatten
    )
  })

  scope :with_category, (lambda { |categories|
    where(category: [*categories])
  })

  def valid_website?
    return if website.empty?
    uri = URI.parse(website)
    errors.add(website, 'is not a valid URL.') unless uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end

  def valid_photo?
    return if photo_url.empty?
    uri = URI.parse(photo_url)
    if uri.path
      # supported image types are png and jpg/jpeg
      errors.add(photo_url, 'is not a valid image URL. Supported image types are png, jpg, and jpeg.') unless uri.is_a?(URI::HTTP) && !uri.host.nil? && uri.path.match(/\.(png|jpg|jpeg)\Z/i)
    else
      errors.add(photo_url, 'is not a valid image URL.')
    end
  rescue URI::InvalidURIError
    false
  end

  def fb?
    return false if fbID.nil?
    !fbID.empty?
  end

  # NOTE: these may need to be updated
  def self.categories
    ['College & University', 'Community Organization', 'Community Services', 'Education',  'Political Organization', 'Religious Organization', 'Science', 'Technology & Engineering', 'Camera/Photo', 'Website', 'Magazine', 'Newspaper', 'Radio Station', 'Sports Team', 'Theatrical Productions']
  end

  private

  def format_url
    self.website = "http://#{website}" unless website.blank? || website[/^https?/]
  end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :logged_in?, only: %i[new create edit update destroy]
  before_action :set_org, only: %i[show edit update destroy]

  # GET /orgs
  # GET /orgs.json
  def index
    default_og_params('Organizations')
    @filterrific = initialize_filterrific(
      Org,
      params[:filterrific],
      select_options: { with_category: Org.categories }
    ) || return
    @orgs = @filterrific.find.sort_by(&:name)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
    @org = Org.find(params[:id])
    meta_img = @org.photo_url.nil? ? og_fallback : @org.photo_url
    set_meta_tags og: {
      title: "#{@org.name} on Events@Penn",
      type:  'website',
      description: @org.bio,
      image: meta_img
    }
    set_meta_tags twitter: {
      card: 'summary',
      title: "#{@org.name} on Events@Penn",
      image: meta_img
    }
    ScrapeNewEventsJob.perform_later(@org) if @org.fb? && user_signed_in?
  end

  # GET /orgs/new
  def new
    @org = Org.new
  end

  def new_from_fb
    org_params = params['fb_page']
    @org = Org.new(name: org_params['name'], category: org_params['category'],
                   fbID: org_params['id'], bio: org_params['about'],
                   website: org_params['website'],
                   photo_url: org_params['image_large'])
  end

  # GET /orgs/1/edit
  def edit; end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = Org.new(org_params)

    if @org.save
      current_user.orgs << @org
      ScrapeNewEventsJob.perform_later(@org) if @org.fb?
      redirect_to @org, notice: "#{@org.name} was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    if @org.update(org_params)
      redirect_to @org, notice: "#{@org.name} was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    redirect_to orgs_url, notice: "#{@org.name} was successfully deleted."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_org
    if Org.exists?(params[:id])
      @org = Org.find(params[:id])
    else
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def org_params
    params.require(:org).permit(:name, :bio, :fbID, :category, :website, :photo_url)
  end

  def logged_in?
    render file: 'public/403.html', status: :forbidden, layout: false unless user_signed_in?
  end
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/orgs/_form.html.erb
<%= form_with(model: org, local: true) do |form| %>
  <% if org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(org.errors.count, "error") %> prohibited this org from being saved:</h2>
      <ul>
      <% org.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :org_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :bio, id: :org_bio, class: 'form-control description' %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, Org.categories, {}, { class: 'form-control' } %>
  </div>

  <%= form.hidden_field :fbID, id: :org_fbID %>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website, id: :org_website, class: 'form-control' %>
  </div>

  <div class="field">
    <%= label_tag 'photo_url', 'Photo URL' %>
    <%= form.text_field :photo_url, id: :org_photo_url, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit @org.new_record? ? 'Create Organization' : 'Update Organization', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/orgs/_list.html.erb
<div id="filterrific_results">
  <div class="row">
    <div class="panel panel-default filled list-all">
      <% @orgs.each do |org| %>
        <div class="row">
          <%= link_to org.name, org %>
        </div>
      <% end %>
      <% if @orgs.empty? %>
        <div class="row">
          No organizations found! Try different filters.
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orgs/edit.html.erb
<% @title = "Editing #{@org.name}" %>
<div class="col-sm-6 right-hand-panel">
  <div class="panel panel-default filled add-org-fb-form">
    <h3 class="org-headers">Edit Organization: <%= link_to @org.name, @org %></h3>
    <%= render 'form', org: @org %>
  </div>
</div>

app/views/orgs/index.html.erb
<% @title = "Organizations" %>
<% unless notice.blank? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="col-lg-8">
  <div class="row page-title">
    <h1 class="pill">Organizations</h1>
  </div>
  <div class="row">
    <%= form_for_filterrific @filterrific do |f| %>
      <% if user_signed_in? %><div class="col-sm-4 list-search">
      <% else %><div class="col-sm-6 list-search">
      <% end %>
        <%= f.text_field(
          :search_query,
          class: 'form-control filterrific-periodically-observed',
          placeholder: 'Search organizations…'
        ) %>
      </div>
      <% if user_signed_in? %><div class="col-sm-4 list-categories">
      <% else %><div class="col-sm-6 list-categories">
      <% end %>
        <%= f.select(
          :with_category,
          @filterrific.select_options[:with_category],
          { include_blank: 'Any category' },
          { class: 'form-control filter' }
        ) %>
      </div>
      <% if user_signed_in? %>
        <div class="col-sm-4 list-add">
          <a class="btn btn-info list-add-btn" href="/orgs/new">Add an Organization</a>
        </div>
      <% end %>
    <% end %>
  </div>

  <%= render(
    partial: 'orgs/list',
    locals: { orgs: @orgs }
  ) %>
</div>

app/views/orgs/index.js.erb
<% js = escape_javascript(
  render(partial: 'orgs/list', locals: { orgs: @orgs })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/orgs/new.html.erb
<% @title = "Create an Organization" %>
<h1 class="pill">Add Organization</h1>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default filled list-all add-org-form">
      <div class="row">
        <h3 class="org-headers">From Facebook</h3>
        <p class="org-headers">Import the details from Facebook organizations that you manage. You'll be able to edit this information after importing.</p>
      </div>
      <% unless user_fb_pages.nil? %>
        <% user_fb_pages.each do |page| %>
          <% fb_page = FbGraph2::Page.new(page.id).authenticate(access_token) %>
          <% fb_page = fb_page.fetch(fields: 'name,about,category,link,website,picture') %>
          <% page = fb_page.raw_attributes %>
          <% page['image_large'] = fb_page.picture(:large).url %>
          <div class="row">
            <%= link_to page[:name], orgs_new_fb_path(fb_page: page), method: :post %> <br>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="col-md-6 right-hand-panel">
    <div class="panel panel-default filled add-org-form">
      <h3 class="org-headers">From Scratch</h3>
      <p>We recommend connecting your organization's Facebook with Events@Penn, because we'll be able to pull all of your events automatically. If you don't want to do that, though, use this form.</p>
      <%= render 'form', org: @org %>
    </div>
  </div>
</div>

app/views/orgs/new_from_fb.html.erb
<% @title = "Create an Organization" %>
<div class="col-sm-6 right-hand-panel">
  <div class="panel panel-default filled add-org-fb-form">
    <h3 class="org-headers">Edit Information from Facebook</h3>
    <p>We've gathered all the information we could from your organization's Facebook page. Feel free to edit anything you want different!</p>
    <%= render 'form', org: @org %>
  </div>
</div>

app/views/orgs/show.html.erb
<%= render 'microdata/org' %>

<% @title = @org.name %>
<div class="page-title">
  <h1 class="pill"><%= @org.name %></h1>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">About <%= @org.name %>
        <% if @org.users.include? current_user %>
          <%= link_to 'Edit', edit_org_path(@org), { class: 'pull-right' } %>
        <% end %>
        </h3>
      </div>

      <div class="panel-body">
        <% unless @org.photo_url.empty? %>
          <img class="img img-responsive" src="<%= @org.photo_url %>" alt="<%= @org.name%> photo">
        <% end %>

        <% unless @org.bio.empty? %>
          <h3 class="org-headers">Description:</h3>
          <p><%= @org.bio %></p>
        <% end %>

        <% unless @org.website.empty? %>
        <div>
          <a href="<%= @org.website %>" target="_blank">
            <%= image_tag "social/website", class: 'social-icon' %>
          </a>
          <a href="<%= @org.website %>" target="_blank">
            <p><%= @org.name %> Online</p>
            <small><em><%= @org.website %></em></small>
          </a>
        </div>
        <% end %>
        <br>
        <% if @org.fb? %>
        <div>
          <a href="https://facebook.com/<%= @org.fbID %>" target="_blank">
            <%= image_tag "social/facebook", class: 'social-icon' %>
          </a>
          <a href="https://facebook.com/<%= @org.fbID %>" target="_blank">
            <p><%= @org.name %> on Facebook</p>
          </a>
          <div class="likebox-wrapper">
            <div class="fb-like" data-href="https://facebook.com/<%= @org.fbID %>" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
          </div>
        </div>
        <% end %>

        <% if @org.users.include? current_user %>
          <h3>Admins:</h3>
          <ul>
            <% @org.users.each do |user| %>
              <li><%= link_to user.full_name, user %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6 right-hand-panel">
    <%# Upcoming Events %>
    <% upcoming = @org.events.where('end_date >= ?', Time.new).sort_by(&:start_date) %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Upcoming Events</h3>
      </div>
      <div class="panel-body list-all show">
        <% if upcoming.empty? %>
        <div class="row">
          <%= @org.name %> has no upcoming events.
        </div>
        <% end %>
        <% upcoming.each do |event| %>
          <div class="row">
            <%= link_to event.title, event %> on <%= event.start_date.strftime("%A, %B %d, %Y") %>
          </div>
        <% end %>
      </div>
    </div>

    <%# Past Events %>
    <% past = @org.events.where('end_date < ?', Time.new).sort_by(&:start_date).reverse %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Past Events</h3>
      </div>
      <div class="panel-body list-all show">
        <% if past.empty? %>
        <div class="row">
          <%= @org.name %> has no past events.
        </div>
        <% end %>
        <% past.each do |event| %>
          <div class="row">
            <%= link_to event.title, event %> on <%= event.start_date.strftime("%A, %B %d, %Y") %>
          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>