config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :events
  resources :orgs
  resources :users
  root to: 'application#index'

  # Pages
  get '/about' => 'application#about'

  # Auth & Sessions
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'

  # Orgs
  post '/orgs/new/fb' => 'orgs#new_from_fb'

  # Day View
  get '/events/day/:date' => 'events#show_day'

  # Sentry endpoint for testing
  # get '/sentry' => 'sentry#exception'
end

app/models/event.rb
class Event < ApplicationRecord
  filterrific(available_filters: %i[search_query with_category])

  belongs_to :org
  validates :title, :location, presence: true
  validates :featured_snippet, length: {maximum: 200}
  validate :dates_present?
  validate :valid_dates?
  validate :category?

  before_validation :set_category

  scope :search_query, (lambda {|query|
    return nil if query.blank?
    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)
    # bracket with '%' to search anywhere in event name/org
    terms = terms.map {|term| '%' + term + '%'}
    # SQL query
    where(
        terms.map {'LOWER(events.title) LIKE ?'}.join(' AND '),
        *terms.map {|e| [e]}.flatten
    )
  })

  scope :with_category, (lambda {|categories|
    where(display_category: [*categories])
  })

  def dates_present?
    return unless start_date.nil? || end_date.nil?
    errors.add(title, 'must have dates and times.') if event_date.nil? && start_date.nil? && end_date.nil?
    if event_date.nil?
      errors.add(title, 'must have start time.') if start_date.nil?
      errors.add(title, 'must have end time.') if end_date.nil?
      self.event_date = start_date.to_date unless start_date.nil?
    else
      self.start_date = event_date
      self.end_date = start_date + 86_399
      event_date.to_date
    end
  end

  def valid_dates?
    if end_date.nil?
      errors.add(title, 'must have an end time.') unless all_day
    else
      errors.add(title, 'must end after start time.') unless start_date < end_date
    end
  end

  def category?
    self.display_category = 'Other' unless Event.categories.include?(display_category)
  end

  def set_category
    self.display_category = category if Event.categories.include?(category)
    return if display_category
    self.category = 'OTHER' if category.nil?
    case category
      when 'CLASS_EVENT'
        self.display_category = 'Academic'
      when 'ART_EVENT', 'ART_FILM', 'BOOK_EVENT', 'EVENT_ART', 'EVENT_LITERATURE', 'MOVIE_EVENT'
        self.display_category = 'Arts'
      when 'SPORTS_EVENT', 'FITNESS'
        self.display_category = 'Athletic'
      when 'NETWORKING'
        self.display_category = 'Career and Professional'
      when 'EVENT_CAUSE', 'CAUSES'
        self.display_category = 'Causes'
      when 'FUNDRAISER', 'VOLUNTEERING'
        self.display_category = 'Charity and Community Service'
      when 'CONFERENCE_EVENT', 'MEETUP', 'WORKSHOP'
        self.display_category = 'Conferences, Meetings and Workshops'
      when 'COMMUNITY'
        self.display_category = 'Ethnic and Cultural'
      when 'EVENT_FOOD', 'FOOD_DRINK', 'FOOD_TASTING', 'DINING_EVENT'
        self.display_category = 'Food'
      when 'HEALTH_WELLNESS'
        self.display_category = 'Health and Wellness'
      when 'LECTURE'
        self.display_category = 'Lectures and Speakers'
      when 'FESTIVAL_EVENT', 'MUSIC', 'MUSIC_EVENT', 'COMEDY_EVENT', 'DANCE_EVENT', 'THEATER_EVENT', 'THEATER_DANCE'
        self.display_category = 'Music, Theater and Performances'
      when 'RELIGION', 'RELIGIOUS_EVENT'
        self.display_category = 'Religious and Spiritual'
      when 'NIGHTLIFE', 'PARTIES_NIGHTLIFE'
        self.display_category = 'Social'
      else
        self.display_category = 'Other'
    end
  end

  def fb?
    return false if fbID.nil?
    !fbID.empty?
  end

  def self.get_date_events(events)
    categories = events.group_by(&:display_category).to_a

    display = []
    categories.each do |set|
      display << [set[0], set[1].length]
    end

    display.sort_by! {|cat| cat[1]}.reverse!
  end

  def self.categories
    ['Academic', 'Arts', 'Athletic', 'Career and Professional', 'Causes',
     'Charity and Community Service', 'Conferences, Meetings and Workshops',
     'Ethnic and Cultural', 'Food', 'Health and Wellness',
     'Lectures and Speakers', 'Music, Theater and Performances', 'Political',
     'Religious and Spiritual', 'Social', 'Other']
  end

  def self.editors_picks(limit)
    Event.where(featured: true).limit(limit)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in?, only: %i[new create edit update destroy]
  before_action :set_event, only: %i[show edit update destroy]
  before_action :init_filter, only: %i[new create edit update]

  # GET /events
  # GET /events.json
  def index
    default_og_params('Events')
    if params['start_date']
      min = Date.parse(params['start_date'])
      max = Date.parse(params['start_date']) + 1.day
      @events = Event.where('(start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?) OR (start_date < ? AND end_date >= ?)', min, max, min, max, min, max)
    else
      @events = Event.where('end_date >= ?', Time.new) # only future events
      init_filter
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    meta_img = @event.org.photo_url.nil? ? og_fallback : @event.org.photo_url
    set_meta_tags og: {
      title: "#{@event.title} on Events@Penn",
      type:  'website',
      image: meta_img
    }
    set_meta_tags twitter: {
      card: 'summary',
      title: "#{@event.title} on Events@Penn",
      image: meta_img
    }
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    new_event_params = event_params
    new_event_params['org'] = Org.find(event_params['org'])
    new_event_params['location_lat'] = params['lat']
    new_event_params['location_lon'] = params['lng']

    @event = Event.new(new_event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_url, notice: "#{@event.title} was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    new_event_params = event_params
    new_event_params['org'] = Org.find(event_params['org'])

    respond_to do |format|
      if @event.update(new_event_params)
        format.html { redirect_to @event, notice: "#{@event.title} was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "#{@event.title} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def init_filter
    @filterrific = initialize_filterrific(
      Event,
      params[:filterrific],
      select_options: {
        with_category: Event.categories
      }
    ) || return
    @events = @filterrific.find.sort_by(&:start_date)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    if Event.exists?(params[:id])
      @event = Event.find(params[:id])
    else
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :fbID, :start_date, :end_date, :event_date, :description, :location, :category, :twentyone, :recurring, :recurrence_freq, :recurrence_amt, :all_day, :org)
  end

  def logged_in?
    render file: 'public/403.html', status: :forbidden, layout: false unless user_signed_in?
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_editors_picks.html.erb
<% Event.editors_picks(4).each do |event| %>
    <p><strong><%= link_to event.title, event_path(event) %></strong>&nbsp;<%= event.featured_snippet %></p>
<% end %>

app/views/events/_form.html.erb
<% content_for :head do %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB7aeyuw86VtqB9Qxclf5GJ1DUlNZhSuZY&libraries=places"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/geocomplete/1.7.0/jquery.geocomplete.min.js"></script>
<% end %>

<%= form_with(model: event, local: true, class: 'form-group') do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :fbID, id: :event_fbID %>

  <%= form.label :event_title, "Event Name" %>
  <%= form.text_field :title, id: :event_title, class: 'form-control' %>
  <%= form.label :org, "Host Organization" %>
  <%= form.select 'org', options_from_collection_for_select(current_user.orgs, :id, :name), {}, { class: 'form-control' } unless current_user.orgs.empty? %>
  <%= form.label :category %>
  <%= form.select :category, Event.categories, {}, { class: 'form-control' } %>

  <div class="checkbox">
    <label>
      <%= form.check_box :twentyone, id: :event_twentyone, class: 'form-check-input checkbox-inline' %> Is this a 21+ event?
    </label>
  </div>

  <%= form.label :location %>
  <%= form.text_field :location, id: :event_location, class: 'form-control', 'data-geo': 'formatted_address' %>
  <input name="lat" type="text" style="display:none;">
  <input name="lng" type="text" style="display:none;">

  <div class="checkbox">
    <label>
      <%= form.check_box :all_day, id: :event_all_day, class: 'form-check-input checkbox-inline', id: 'all-day-event' %> Is this an all-day event?
    </label>
  </div>

  <div class="row" id="date-and-time">
    <div class="col-sm-6 add-event-start">
      <%= form.label :start_date, "Start Time" %>
      <%= form.datetime_select :start_date %>
    </div>
    <div class="col-sm-6 add-event-end">
      <%= form.label :end_date, "End Time" %>
      <%= form.datetime_select :end_date %>
    </div>
  </div>
  <div id="date">
    <%= form.label :event_date, "Event Date" %>
    <%= form.date_select :event_date %>
  </div>

  <script type="text/javascript">
    $(function () {
      $('#start_date').datetimepicker();
      $('#end_date').datetimepicker({
        useCurrent: false
      });
      $('#event_date').datetimepicker({
        format: 'MM/dd/YY'
      });

      $("#start_date").on("dp.change", function (e) {
          $('#end_date').data("DateTimePicker").minDate(e.date);
      });
      $("#end_date").on("dp.change", function (e) {
          $('#start_date').data("DateTimePicker").maxDate(e.date);
      });

      var all_day = document.getElementById('all-day-event');
      var date_time = document.getElementById('date-and-time');
      var date = document.getElementById('date');
      if (all_day.checked) {
        date.style['display'] = 'block';
        date_time.style['display'] = 'none';
      } else {
        date.style['display'] = 'none';
        date_time.style['display'] = 'block';
      }

      all_day.onchange = function() {
        if(this.checked) {
         date.style['display'] = 'block';
         date_time.style['display'] = 'none';
        } else {
         date.style['display'] = 'none';
         date_time.style['display'] = 'block';
        }
      };

      $(date).on('click', function() {
        var extra_cal = document.getElementById('ui-datepicker-div');
        if (extra_cal) {
          $(extra_cal).remove();
        };
      });
    });
    setTimeout(function () {
      $("#event_location").geocomplete({ details: "form" });
    }, 500);
  </script>

  <%= form.label :description %>
  <%= form.text_area :description, id: :event_description, class: 'form-control description' %>

  <%= form.submit class: 'btn btn-success' %>
<% end %>

app/views/events/_list.html.erb
<div id="filterrific_results">
  <div class="row">
    <%# Upcoming Events %>
    <div class="panel panel-default filled list-all">
      <% upcoming = @events.select { |e| e.end_date >= Time.new } %>
      <% upcoming.each do |event| %>
        <div class="row">
          <%= link_to event.title, event %> by
          <em><%= link_to event.org.name, event.org %></em> on
          <em>
            <%= event.start_date.strftime("%A, %B %d at %l:%M %P") unless event.all_day %>
            <%= event.start_date.strftime("%A, %B %d") if event.all_day %>
          </em>
        </div>
      <% end %>
      <% if upcoming.empty? %>
        <div class="row">
          No events found! Try different filters.
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<% @title = "Editing #{@event.title}" %>

<div class="col-sm-6 right-hand-panel">
  <div class="panel panel-default filled edit-event-form">
    <h3 class="org-headers">Edit Event: <%= link_to @event.title, @event %></h3>
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/index.html.erb
<% @title = "Events" %>

<% unless notice.blank? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<div class="col-lg-8">
  <div class="row page-title">
    <h1 class="pill">Upcoming Events</h1>
  </div>
  <div class="row">
    <% if ENV['RAILS_ENV'] != 'test' %>
    <%= form_for_filterrific @filterrific do |f| %>
      <% if user_signed_in? && current_user.orgs.any? %>
        <div class="col-sm-4 list-search">
      <% else %>
        <div class="col-sm-6 list-search">
      <% end %>
        <%= f.text_field(
          :search_query,
          class: 'form-control filterrific-periodically-observed',
          placeholder: 'Search events…'
        ) %>
      </div>
      <% if user_signed_in? && current_user.orgs.any? %>
        <div class="col-sm-4 list-categories">
      <% else %>
        <div class="col-sm-6 list-categories">
      <% end %>
        <%= f.select(
          :with_category,
          @filterrific.select_options[:with_category],
          { include_blank: 'Any category' },
          { class: 'form-control filter' }
        ) %>
      </div>
      <% if user_signed_in? && current_user.orgs.any? %>
        <div class="col-sm-4 list-add">
          <a class="btn btn-info list-add-btn" href="/events/new">Add an Event</a>
        </div>
      <% end %>
    <% end %>
    <% end %>
  </div>

  <%= render(
    partial: 'events/list',
    locals: { events: @events }
  ) %>
</div>

app/views/events/index.js.erb
<% js = escape_javascript(
  render(partial: 'events/list', locals: { events: @events })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/events/new.html.erb
<% @title = "Create an Event" %>
<h1 class="pill">Add Event</h1>

<div class="row">
  <div class="col-md-6">
    <div class="panel-new-event">
      <div class="row">
		<%= render 'form', event: @event %>
	  </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<% @title = @event.title %>
<% content_for :head do %>
<%= render 'microdata/event' %>

<script>
  function renderMap() {
    var loc = {lat: <%= @event.location_lat %>, lng: <%= @event.location_lon %> };
    var cen = {lat: <%= @event.location_lat %> + .0025, lng: <%= @event.location_lon %> };
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: cen,
      mapTypeControl: false,
      streetViewControl: false
    });
    var marker = new google.maps.Marker({
      position: loc,
      map: map
    });
    var infowindow = new google.maps.InfoWindow({
      content: `
        <center>
          <p><b><%= @event.location %></b></p>
          <br />
          <p><%= @event.title %> by <i><%= @event.org.name %></i></p>
        </center>
      `
    }).open(map, marker);
    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }

  function initMap() {
    $(document).ready(function() { renderMap() });
    $(document).on('turbolinks:load', function(e) { renderMap() });
  }
</script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB7aeyuw86VtqB9Qxclf5GJ1DUlNZhSuZY&callback=initMap">
  </script>
<% end %>
<div class="page-title">
  <h1 class="pill"><%= @event.title %></h1>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="panel panel-default filled show-event">
      <p class="p-large mb5"><strong>Location:</strong> <%= @event.location %></p>

      <p class="p-large mb5"><strong>Time:</strong>
      <% if @event.start_date.to_date == @event.end_date.to_date %>
        <% if @event.all_day %>
          <%= @event.start_date.strftime("%A, %B %d, %Y, all day") %>
        <% else %>
          <%= @event.start_date.strftime("%A, %B %d, %Y from %l:%M %P") %>
          to <%= @event.end_date.strftime("%l:%M %P") %>
        <% end %>
      <% else %>
        <%= @event.start_date.strftime("%A, %B %d, %Y at %l:%M %P") %>
        to <%= @event.end_date.strftime("%A, %B %d, %Y at %l:%M %P") %>
      <% end %>
      </p>

      <p class="p-large mb5"><strong>Hosted by:</strong> <%= link_to @event.org.name, @event.org %></p>

      <p class="p-large mb5"><strong>Category:</strong> <%= @event.display_category %></p>

      <% if @event.twentyone %>
        <p class="p-large mb5">This is a 21+ event!</p>
      <% end %>

      <% unless @event.description.blank? %>
        <p class="p-large mb5 mt20"><strong>Description:</strong></p>
        <p><%= @event.description %></p>
      <% end %>

      <% if @event.fb? %>
      <div>
        <a href="https://facebook.com/events/<%= @event.fbID %>" target="_blank">
          <%= image_tag "social/facebook", class: 'social-icon' %>
        </a>
        <a href="https://facebook.com/events/<%= @event.fbID %>" target="_blank"><%= @event.title %> on Facebook</a>
        <div id="rsvp">
          <a class='fb-button' href="https://facebook.com/events/<%= @event.fbID %>">RSVP</a>
        </div>
        <div class="faces" id="faces"></div>
      </div>
      <% end %>

      <% if @event.org.users.include? current_user %>
        <hr>
        <%= link_to 'Edit this event', edit_event_path(@event) %>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6 right-hand-panel">
    <% if @event.fb? %>
    <div class="panel panel-default filled fb-info-panel">
      <div id="fb-cover-photo"></div>
      <div class="row text-center fb-attendee-count">
        <div class="col-xs-4" id="fb-going">
        </div>
        <div class="col-xs-4" id="fb-interested">
        </div>
        <div class="col-xs-4" id="fb-invited">
        </div>
      </div>
    </div>
    <% end %>
    <% unless (@event.location_lat.nil? && @event.location_lon.nil?) || (@event.location_lat == 0 && @event.location_lon == 0) %>
      <div class="panel panel-default filled">
        <div id="map"></div>
      </div>
    <% end %>
  </div>
</div>

<% if @event.fb? && user_signed_in? %>
<script type="text/javascript">
function getFBEventInfo() {
  FB.api(
    "/<%= @event.fbID %>/attending?fields=id,rsvp_status,name,picture{url}&limit=15&access_token=<%= access_token%>",
    function (response) {
      if (response && !response.error) {
        for (var i = 0; i < response.data.length; i++) {
          var attendee = response.data[i];
          var url = 'http://www.facebook.com/' + attendee.id
          var img = attendee.picture.data.url
          $('#faces').append("<a class='face' alt='" + attendee.name + "' href='" + url + "'><img src=" + img + "></img></a>")
        }
      }
      if (response.error) {
        console.error(response);
      }
    }
  );

  FB.api(
    "/<%= @event.fbID %>?fields=id,attending_count,interested_count,declined_count,noreply_count,can_guests_invite,ticket_uri,cover&access_token=<%= access_token%>",
    function (response) {
      if (response && !response.error) {
        if (response.ticket_uri != null && response.ticket_uri != "") {
          $('#rsvp').append("<a class='fb-button' href='" + response.ticket_uri +"' target='_blank'>Tickets</a>")
        }
        $('#rsvp').append("&nbsp;" + response.attending_count + " people are attending.")
        $('#fb-cover-photo').append("<img src=" + response.cover.source + "></img>");
        $('#fb-going').prepend(response.attending_count + "<em>Attending</em>")
        $('#fb-interested').prepend(response.interested_count + "<em>Interested</em>")
        $('#fb-invited').prepend(response.noreply_count + "<em>Invited</em>")
      }
      if (response.error) {
        console.error(response);
      }
    }
  );
};
</script>
<% end %>

app/views/events/show_day.html.erb
<h2><%= @current_date %></h2>
<% @events_today.each do |event| %>
  <div class="col-xs-3 day-view time">
    <%= event.start_date.strftime("%l %p") %>
  </div>
  <div class="col-xs-9 day-view event  <%= event.display_category.split(/,\s*/)[0].downcase %>">
    <strong><%= event.title %></strong><br>
    <%= event.location %>
    <a href="/events/<%= event.id %>" class="pull-right more"><em>more&nbsp</em>&#10140;</a>
  </div>
<% end %>