config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :events
  resources :orgs
  resources :users
  root to: 'application#index'

  # Pages
  get '/about' => 'application#about'

  # Auth & Sessions
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'

  # Orgs
  post '/orgs/new/fb' => 'orgs#new_from_fb'

  # Day View
  get '/events/day/:date' => 'events#show_day'

  # Sentry endpoint for testing
  # get '/sentry' => 'sentry#exception'
end

app/views/layouts/_head.html.erb
<%# Shared <HEAD> element tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= @title.nil? ? "Events@Penn" : "#{@title} | Events@Penn" %></title>
<% if @meta_description.present? %>
  <meta name="description" content="<%= @meta_description %>">
<% end %>

<%= display_meta_tags site: 'Events@Penn' %>
<meta name="fb:app_id" content="<%= Rails.application.secrets.fb_app_id %>">

<link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,900" rel="stylesheet">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>

<%# Google DFP ads, analytics %>
<script async="async" src="https://www.googletagservices.com/tag/js/gpt.js"></script>
<script>
  var googletag = googletag || {};
  googletag.cmd = googletag.cmd || [];
</script>
<script>
  googletag.cmd.push(() => {
    googletag.defineSlot('/12234093/DP.com-Leaderboard', [728, 90], 'div-gpt-ad-1529280717739-0').addService(googletag.pubads());
    googletag.defineSlot('/12234093/DP.com-mobile-leaderboard', [320, 50], 'div-gpt-ad-1529280717739-1').addService(googletag.pubads());
    googletag.defineSlot('/12234093/DP.com-Top-Rectangle', [300, 250], 'div-gpt-ad-1529280717739-2').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.enableServices();
  });
</script>
<% if Rails.env.production? %>
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-12991053-1', 'auto');
</script>
<% end %>
<%= csrf_meta_tags %>

<% if content_for? :head %>
  <%= yield :head %>
<% end %>
<%# favicons %>
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="manifest" href="/favicons/manifest.json">
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#aa1e22">
<link rel="shortcut icon" href="/favicons/favicon.ico">
<meta name="msapplication-config" content="/favicons/browserconfig.xml">
<meta name="apple-mobile-web-app-title" content="Events@Penn">
<meta name="application-name" content="Events@Penn">
<meta name="theme-color" content="#aa1e22">

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_month_cal.html.erb
<%= month_calendar(attribute: :start_date, end_attribute: :end_date, events: @events) do |d, events| %>
  <div class="date" data-date="<%= "#{d.strftime("%Y-%m-%d")}" %>">
    <span class="date-num"><%= d.day %></span>
    <span class="mobile-weekday">
      <% weekdays = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday] %>
      <%= weekdays[d.wday] %>
    </span>
  </div>
  <a href=<%="/events/day/#{d.strftime("%Y-%m-%d")}"%>>
    <% date_events = Event.get_date_events(events) %>
    <% see_all = date_events.length > 3 %>
    <% date_events = date_events.take(3) if see_all %>
    <% date_events.each do |event| %>
      <div class="calendar-event <%= event[0].split(', ').first.downcase %>">
        <%= pluralize(event[1], "#{event[0]} Event") %>
      </div>
    <% end %>
    <% if see_all %>
      <div class="more-events">
        See all (<%= events.length %>)
      </div>
    <% end %>
  </a>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to "Admin", '/admin' %></li>
  <% end %>
  <li><%= link_to "Welcome, #{current_user.first_name}", current_user %></li>
  <li><%= link_to 'Sign out', signout_path %></li>
<% else %>
  <li><%= link_to 'Sign in', signin_path %></li>
<% end %>

app/views/layouts/_navbottom.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <a href="https://www.facebook.com/eventsatpenn" target="_blank">
      <%= image_tag "social/facebook", class: 'social-bottom' %>
    </a>
    <a href="https://www.twitter.com/_eventsatpenn" target="_blank">
      <%= image_tag "social/twitter", class: 'social-bottom' %>
    </a>
    <a href="mailto:eventsatpenn@thedp.com" target="_blank">
      <%= image_tag "social/gmail", class: 'social-bottom' %>
    </a>
    <a href="http://www.thedp.com/" class="navbar-brand" target="_blank">
      Powered by <%= image_tag "logos/dp", class: 'logo-bottom' %>
    </a>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">
        <%= image_tag "logos/EventsAtPennLogotype", class: "navbar-logo" %>
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', '/about' %></li>
<li><%= link_to 'Organizations', orgs_path %></li>
<li><%= link_to 'Events', events_path %></li>

app/views/layouts/_scripts.html.erb
<%# scripts to go right after opening of body tag %>

<%# FB API %>
<div id="fb-root"></div>
<script>
window.fbAsyncInit = function() {
  FB.init({
    appId   : '<%= Rails.application.secrets.fb_app_id %>',
    status  : true,
    cookie  : true,
    xfbml   : true,
    version : 'v2.9'
  });

  if (typeof(getFBEventInfo) != "undefined") {
    getFBEventInfo();
  }
};
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10&appId=<%= Rails.application.secrets.fb_app_id %>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

// Compatibility with Turbolinks 5
(function($) {
  var fbRoot;

  function saveFacebookRoot() {
    if ($('#fb-root').length) {
      fbRoot = $('#fb-root').detach();
    }
  };

  function restoreFacebookRoot() {
    if (fbRoot != null) {
      if ($('#fb-root').length) {
        $('#fb-root').replaceWith(fbRoot);
        if (typeof(getFBEventInfo) != "undefined") {
          getFBEventInfo();
        }
      } else {
        $('body').append(fbRoot);
      }
    }

    if (typeof FB !== "undefined" && FB !== null) { // Instance of FacebookSDK
      FB.XFBML.parse();
    }
  };

  document.addEventListener('turbolinks:request-start', saveFacebookRoot)
  document.addEventListener('turbolinks:load', restoreFacebookRoot)
}(jQuery));
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/scripts' %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid main">
        <% if mobile_device? %>
        <div>
        <% else %>
          <div class="col-app">
        <% end %>
          <%= render 'layouts/messages' %>
          <%= render 'ads/leaderboard' %>
          <%= yield %>
        </div>

        <% unless mobile_device? %>
          <div class="col-ads">
            <%= render 'ads/rectangle1' %>
            <%= render 'ads/rectangle2' %>
          </div>
        <% end %>
      </div>
    </main>
    <div>
      <%= render 'ads/rectangle1' if mobile_device? %>
      <%= render 'ads/rectangle2' if mobile_device? %>
    </div>
    <footer>
      <%= render 'layouts/navbottom' %>
    </footer>
  </body>
</html>

app/views/layouts/calendar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container-fluid main">
        <%= render 'layouts/messages' %>
        <div class="row">
          <div class="col-md-8">
            <%= form_for_filterrific @filterrific do |f| %>
              <div class="col-sm-3 list-categories">
              <%= f.select(
                :with_category,
                @filterrific.select_options[:with_category],
                { include_blank: 'Any category' },
                { class: 'form-control pull-left calendar-categories' }
              ) %>
              </div>
            <% end %>
            <% if user_signed_in? && !current_user.orgs.empty? %>
            <div class="col-sm-3 center calendar-create">
              <a class="btn btn-info pull-right add-event-btn" href="/events/new">Add an Event</a>
            </div>
            <% end %>
            <div id="filterrific_results">
              <%= render(
                partial: 'layouts/month_cal',
                locals: { events: @events }
              ) %>
            </div>
          </div>
          <div class="col-md-4">
              <div class="panel-date">
                <% if current_page?(new_event_path) %>
                  <h3 class="new-event">Add Event</h3>
                <% end %>
              </div>
              <div class="panel panel-default filled calendar-sidebar">
                <div class="panel-body">
                  <%= yield %>
                </div>
              </div>
            <%= render 'ads/rectangle1' if mobile_device? %>
            <%= render 'ads/rectangle2' if mobile_device? %>
          </div>
        </div>
      </div>
    </main>
    <footer>
      <%= render 'layouts/navbottom' %>
    </footer>
  </body>
</html>

app/views/layouts/calendar.js.erb
<% js = escape_javascript(
  render(partial: 'layouts/month_cal', locals: { events: @events })
) %>
$("#filterrific_results").html("<%= js %>");
$(document).trigger('filtered');